=== danilshvalov/itmo-web-programming/terms/term-6/lab-4/code/task-1/lessons_DTD.dtd
<!ELEMENT lessons (lesson+)>
<!ELEMENT lesson (
  CourseName, 
  ProfessorSurname,
  Semester,
  AcademicHours,
  ControlType,
  Format
)>
<!ATTLIST lesson id ID #REQUIRED>
<!ELEMENT CourseName (#PCDATA)>
<!ELEMENT ProfessorSurname (#PCDATA)>
<!ELEMENT Semester (#PCDATA)>
<!ELEMENT AcademicHours (#PCDATA)>
<!ELEMENT ControlType (#PCDATA)>
<!ELEMENT Format (#PCDATA)>

=== danilshvalov/itmo-web-programming/terms/term-6/lab-4/code/task-1/lessons.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE lessons SYSTEM "lessons_DTD.dtd">
<lessons>
  <lesson id="m1">
    <CourseName>Математика</CourseName>
    <ProfessorSurname>Кольцова</ProfessorSurname>
    <Semester>1</Semester>
    <AcademicHours>108</AcademicHours>
    <ControlType>Экзамен</ControlType>
    <Format>Очный</Format>
  </lesson>
  <lesson id="m2">
    <CourseName>Программирование</CourseName>
    <ProfessorSurname>Осипов</ProfessorSurname>
    <Semester>2</Semester>
    <AcademicHours>144</AcademicHours>
    <ControlType>Зачёт</ControlType>
    <Format>Очно-дистанционный</Format>
  </lesson>
  <lesson id="m3">
    <CourseName>Базы данных</CourseName>
    <ProfessorSurname>Осетрова</ProfessorSurname>
    <Semester>3</Semester>
    <AcademicHours>96</AcademicHours>
    <ControlType>Дифференцированный зачёт</ControlType>
    <Format>Дистанционный</Format>
  </lesson>
</lessons>
